### ISSUE TITLE
How to get the backbone's pretrained weight for e.g. ResNet-50

### ISSUE THREAD

**Issue by Shuaicong97** [OpenGVLab/MUTR#3]
Hi, when I compared the Ref-YouTube-VOS.md in MUTR to ReferFormer, I noticed that in the table there's a missing column about **Pretrain**. I assume that is **[/path/to/backbone_pretrained_weight]**, which I need for Training. And the weight under Model column is for parameter **--resume** which I put into ./results/[backbone]/ckpt/backbone_weight.pth.

My question is, when I run the command "./scripts/dist_train.sh  --backbone [backbone] --backbone_pretrained [/path/to/backbone_pretrained_weight] [other args]", e.g. ./scripts/dist_train.sh --backbone restnet50 --backbone_pretrained [???] What should I put into --backbone_pretrained?

Thank you in advance!

**Comment by shilinyan99** [comment]
The backbone_pretrained of ResNet50 is the pre-trained weight of ResNet50. You can download it at this [https://download.pytorch.org/models/resnet50-0676ba61.pth]

**Comment by shilinyan99** [comment]
The backbone_pretrained of ResNet50 is the pre-trained weight of ResNet50. You can download it at this [R50](https://download.pytorch.org/models/resnet50-0676ba61.pth)
